name = "d1-project12ms"
main = "src/index.ts"
compatibility_date = "2023-08-09"
node_compat = true

[vars]
API_KEY = "123"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "db_astro3_13"
database_id = "123"



